---
- name: Install basic command line tools
  package: name={{ item }} state=present
  with_items:
    - tree
    - htop
    - curl
    - wget
    - inotify-tools
    - nmap
    - ssh

- name: Install media player and codecs
  apt: name={{ item }} state=present
  with_items:
    - mplayer
    - gstreamer1.0-fluendo-mp3
    - gstreamer1.0-libav
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-ugly
    - libavcodec-extra
