---
- name: Add PPA of multiload-ng
  apt_repository: repo=ppa:nilarimogard/webupd8

- name: Install multiload-ng
  apt: package=xfce4-multiload-ng-plugin state=present

- name:  Make sure config paths exist
  file:
    path: "{{ user.homedir }}/.config/xfce4/panel/"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    recurse: yes
    state: directory

- name: Configure multiload-ng
  copy:
    src: multiload-ng-xfce4-13.rc
    dest: "{{ user.homedir }}/.config/xfce4/panel/multiload-ng-xfce4-13.rc"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
